# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sonic-mirror-build

variables:
- group: Debian-Mirror-GPG-VG
jobs:
- job: "Publish Debian Jessie To Stroage Test1"
  variables:
  - group: Debian-Mirror-Jessie
  - group: Debian-Mirror-Storage-Test1
  steps:
  - template: ../templates/prepare-mirror-agent.yaml
  - template: ../templates/prepare-mirror-storage.yaml
    parameters:
      storageAccount: $(StorageAccount)
      storageAccountSasToken: $(storageAccountSasToken)
  - bash: |
      echo "$(sonic-gpg-enc-private-key)" > "encrypted_private_key.gpg"
      scripts/mirror/aptly.sh $(StorageAccount) "$(Distribution)" "$(CreateDB)" "$(sonic-gpg-passphrase)"
    displayName: 'Update and publish debian mirrors by aptly'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

