# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sonic-mirror-build-2
variables:
- group: Debian-Mirror-GPG-VG
- group: Debian-Mirror-Storage-US-East-2
- group: Debian-Mirror-Common
- name: EnableNfs
  value: 'y'
stages:
- stage: InitStage
  jobs:
  - job: InitJob
    steps:
    - template: ../templates/check-cdn-status.yaml
    - bash: |
        MIRROR_VERSION=$(date +%Y%m%d%H%M%S-%N)
        echo "##vso[task.setvariable variable=MIRROR_VERSION;isOutput=true]$MIRROR_VERSION"
      name: InitStep
- stage: PublishToReplicaStage
  dependsOn: InitStage
  variables:
  - name: MIRROR_VERSION
    value: $[ stageDependencies.InitStage.InitJob.outputs['InitStep.MIRROR_VERSION'] ]
  jobs:
  - job: PublishBusterToUSEastReplica
    timeoutInMinutes: 0
    variables:
    - group: Debian-Mirror-Buster
    - name: PublishToReplica
      value: 'y'
    steps:
    - bash: |
        echo "MIRROR_VERSION=$MIRROR_VERSION"
    #- template: ../templates/publish-mirror.yaml
    #  parameters:
    #    updateMirror: 'y'
- stage: MigrateReplicaStage
  dependsOn:
  - InitStage
  - PublishToReplicaStage
  variables:
  - name: MIRROR_VERSION
    value: $[ stageDependencies.InitStage.InitJob.outputs['InitStep.MIRROR_VERSION'] ]
  jobs:
  - job: Test
    steps:
    - bash: |
        echo "MIRROR_VERSION=$MIRROR_VERSION"
      displayName: 'Test'
