# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sonic-mirror-build-2

variables:
- group: Debian-Mirror-GPG-VG
- group: Debian-Mirror-Storage-US-East-2
- group: Debian-Mirror-Common
- name: EnableNfs
  value: 'y'
stages:
- stage: PublishBusterToUSEast
  jobs:
  - job: PublishBusterToUSEastReplica
    timeoutInMinutes: 0
    variables:
    - group: Debian-Mirror-Buster
    - name: PublishToReplica
      value: 'y'
    steps:
    - template: ../templates/check-cdn-status.yaml
    - template: ../templates/publish-mirror.yaml
      parameters:
        updateMirror: 'y'
  - job: PublishBusterToUSEast
    timeoutInMinutes: 0
    dependsOn: PublishBusterToUSEastReplica
    condition: eq(dependencies.PublishBusterToUSEastReplica.outputs['DetermineResult.MIRROR_PUBLISHED'], 'y')
    variables:
    - group: Debian-Mirror-Buster
    - name: PublishToReplica
      value: 'n'
    - name: CreateDB
      value: 'n'
    steps:
    - template: ../templates/migrate-cdn-replica.yaml
      parameters:
        cdnReplicaOriginPriority: '1'
    - template: ../templates/publish-mirror.yaml
      parameters:
        updateMirror: 'n'
    - template: ../templates/migrate-cdn-replica.yaml
      parameters:
        cdnReplicaOriginPriority: '3'
