# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sonic-mirror-build-2

variables:
- group: Debian-Mirror-GPG-VG
- group: Debian-Mirror-Storage-US-East-2
stages:
- stage: PublishBusterToUSEast
  jobs:
  - job: PublishBusterToUSEast
    timeoutInMinutes: 0
    variables:
    - group: Debian-Mirror-Buster
    - name: PublishToReplica
      value: 'n'
    steps:
    - template: ../templates/publish-mirror.yaml
      parameters:
        enableNfs: 'y'
  - job: PublishBusterToUSEasteplica
    timeoutInMinutes: 0
    dependsOn: PublishBusterToUSEast
    variables:
    - group: Debian-Mirror-Buster
    - name: PublishToReplica
      value: 'y'
    - name: CreateDB
      value: 'n'
    steps:
    - template: ../templates/publish-mirror.yaml
      parameters:
        enableNfs: 'y'
