# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: $(AGENT_POOL)

variables:
- group: SONiC-Azure-Key-Vault
- group: Debian-Mirror-Common
- template: debian-mirror-variables.yml
  parameters:
    publishTo: $(PublishTo)

stages:
- stage: Build
  variables:
    JobVar1: var1
    JobVar2: var2
    TestNAME: test1
    MIRROR_COMPONENTS: 'contrib,non-free,main'
    MIRROR_ARICHTECTURES: 'amd64,armhf,arm64'
  jobs:
  - template: ../templates/jobs-template.yml
    parameters:
      preSteps:
      - script: |
          echo "prestep1"
          echo "JobVar1=$JobVar1"
          echo "JOB_NAME=$JOB_NAME"
          echo "TestNAME=$TestNAME"
          echo "TestNAME=$(TestNAME)"
          echo "TESTNAME=$(TESTNAME)"
          echo "MIRROR_COMPONENTS=$MIRROR_COMPONENTS"
          echo "StorageAccountReplica=$(StorageAccountReplica)"
          echo "StorageAccount=$(StorageAccount)"
          echo "MIRROR_ARICHTECTURES=$MIRROR_ARICHTECTURES"
          echo "ScriptEnv1=$ScriptEnv1"
          echo "MIRROR_NAME=$MIRROR_NAME"
          echo "MIRROR_FILESYSTEM=$MIRROR_FILESYSTEM"
          echo "MIRROR_ARICHTECTURES=$MIRROR_ARICHTECTURES"
      postSteps:
      - script: |
          echo "poststep1"
      scriptEnv:
        ScriptEnv1: env1
      stepGroups:
      - name: jessie
        script: |
          echo "ScriptEnv1=$ScriptEnv1"
          echo "JobVar2=$JobVar2"
        variables:
          MIRROR_NAME: jessie
          MIRROR_FILESYSTEM: debian
          MIRROR_URL: 'http://deb.debian.org/debian'
          MIRROR_DISTRIBUTIONS: 'jessie,jessie-updates'
          MIRROR_ARICHTECTURES: 'amd64,armhf'
      - name: stretch
        variables:
          MIRROR_NAME: stretch
          MIRROR_FILESYSTEM: debian
          MIRROR_URL: 'http://deb.debian.org/debian'
          MIRROR_DISTRIBUTIONS: 'stretch,stretch-updates,stretch-backports'
      - name: buster
        variables:
          MIRROR_NAME: buster
          MIRROR_FILESYSTEM: debian
          MIRROR_URL: 'http://deb.debian.org/debian'
          MIRROR_DISTRIBUTIONS: 'buster,buster-updates,buster-backports'
      - name: jessie_security
        variables:
          MIRROR_NAME: debian-security
          MIRROR_FILESYSTEM: debian-security
          MIRROR_URL: 'http://security.debian.org/debian-security'
          MIRROR_DISTRIBUTIONS: 'jessie/updates'
          MIRROR_ARICHTECTURES: 'amd64,armhf'
      - name: stretch_security
        variables:
          MIRROR_NAME: stretch-security
          MIRROR_FILESYSTEM: debian-security
          MIRROR_URL: 'http://security.debian.org/debian-security'
          MIRROR_DISTRIBUTIONS: 'stretch/updates'
      - name: buster_security
        variables:
          MIRROR_NAME: buster-security
          MIRROR_FILESYSTEM: debian-security
          MIRROR_URL: 'http://security.debian.org/debian-security'
          MIRROR_DISTRIBUTIONS: 'buster/updates'
