# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: sonic-mirror-build-2

parameters:
- name: 'platforms'
  type: object
  default:
  - vs:
    prestep:
    targets: 'target/sonic-vs.bin'
    options:
    poststeps:
    - bash:
  - broadcom:
stages:
- stage: Build
  jobs:
  - ${{ each platform in parameters.platforms }}:
    job: ${{ format('Publish_mirror_{0}', platform.key) }}
    timeoutInMinutes: 0
    steps:
    - bash: |
        echo "pre-step"
      displayName: 'pre-step'
