# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: sonic-mirror-build-2

stages:
- stage: Build
  jobs:
  - template: ../templates/jobs-template.yml
    parameters:
      preSteps:
      - script: |
          echo "prestep1"
          echo "JobVar1=$JobVar1"
          echo "ScriptEnv1=$ScriptEnv1"
          echo "MIRROR_NAME=$MIRROR_NAME"
      postSteps:
      - script: |
          echo "poststep1"
      jobVariables:
        JobVar1: var1
        JobVar2: var2
      scriptEnv:
        ScriptEnv1: env1
      stepGroups:
      - name: test
        jobVariables:
          MIRROR_NAME: jessie
          MIRROR_FILESYSTEM: debian
          MIRROR_URL: 'http://deb.debian.org/debian'
          MIRROR_DISTRIBUTIONS: 'jessie,jessie-updates'
          MIRROR_COMPONENTS: 'contrib,non-free,main'
          MIRROR_ARICHTECTURES: 'amd64,armhf'
