# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: sonic-mirror-build-2

parameters:
- name: 'platforms'
  type: object
  default:
  - vs:
    prestep:
    targets: 'target/sonic-vs.bin'
    options:
    poststeps:
    - bash:
  - broadcom:
- name: 'publishjob'
  type: job
  default:
    job:
    steps:
    - bash: |
        echo "test"
stages:
- stage: Build
  jobs:
  - template: ../templates/test-template.yml
