parameters:
- name: 'cdnReplicaOriginPriority'
  type: string
  default: '3'
- name: 'purgeContent'
  type: string
  default: 'y'
steps:
- template: ../templates/debian-mirror-init-agent.yml
- template: ../templates/debian-mirror-init-storage.yml
- template: ../templates/debian-mirror-migrate-cdn-replica.yml
