parameters:
- name: 'mirrorNames'
  type: object
  default:
  - stretch
  - buster
- name: 'publishjob'
  type: job
  default:
    job:
    steps:
    - bash: |
        echo "test"
jobs:
- ${{ each mirrorName in parameters.mirrorNames }}:
  - ${{ each pair in parameters.publishjob }}:
      ${{ if and(ne(pair.key, 'steps'), ne(pair.key, 'job')) }}:
        ${{ pair.key }}: ${{ pair.value }}
    job: ${{ format('Publish_mirror_{0}', replace(mirrorName, '-', '_')) }}
    timeoutInMinutes: 0
    steps:
    - template: ../templates/debian-mirror-init-agent.yml
    - template: ../templates/debian-mirror-init-storage.yml
      parameters:
          mirrorName: ${{ mirrorName }}
          nfsMountPoint: '/$(NFSName)'
    - bash: |
        echo "pre-step"
        MirrorNames=${{ join(',', parameters.mirrorNames) }}
        echo "MirrorNames=$MirrorNames"
        echo "$MirrorNames" > work/_aptly/mirror_names
      displayName: 'pre-step'
    - ${{ parameters.publishjob.steps }}
    - bash: |
        set -e
        azure-pipelines/scripts/mirror/publish-debian-mirror.sh  "$(CreateDB)" "${{ mirrorName }}"
      name: publishMirrorBash
      env:
        PASSPHRASE: $(sonic-gpg-passphrase)
        GPG_KEY: $(sonic-gpg-enc-private-key)
        UPDATE_MIRROR: $(UpdateMirror)
        MIRROR_VERSION: $(MirrorVersion)
        GPG_PUBLIC_KEY2: $(sonic-gpg-public-key-2)
    - bash: |
        echo "post-step"
      displayName: 'post-step'
