parameters:
- name: 'mirrorName'
  type: string
  default: 'none'
- name: 'publishToReplica'
  type: string
  default: 'n'
- name: 'workspace'
  type: string
  default: 'work'
- name: 'enableNfs'
  type: string
  default: 'y'
- name: 'nfsMountPoint'
  type: string
  default: '/nfs_data'
steps:
- bash: |
    WORKSPACE=${{ parameters.workspace }}
    echo "pwd=$(pwd)"
    if [ -z "$WORKSPACE" ]; then
      echo "The workspace is not set." 2>&1
      exit 1
    fi
    [ -e "$WORKSPACE" ] && sudo rm -rf "$WORKSPACE"
    mkdir -p "$WORKSPACE"
  displayName: 'Clean up workspace'
- bash: |
    set -e
    EnableNFS=${{ parameters.enableNfs }}
    WORKSPACE=${{ parameters.workspace }}
    MIRROR_NAME=${{ parameters.mirrorName }}
    NFS_VOLUMN=$(NFSVolumn)
    NFS_MOUNT_POINT=${{ parameters.nfsMountPoint }}
    azure-pipelines/scripts/mirror/mount-nfs.sh "$NFS_MOUNT_POINT" "$NFS_VOLUMN"
    mkdir -p "$NFS_MOUNT_POINT/aptly"
    ln -s "$NFS_MOUNT_POINT/aptly" "$WORKSPACE/_aptly"
    if [ "$MIRROR_NAME" == "none" ]; then
      echo "Skip to make soft link"
      exit 0
    fi

    APTLY_POOL_PATH=$WORKSPACE/pool
    NFS_MIRROR_PATH=$NFS_MOUNT_POINT/aptly/$MIRROR_NAME
    echo "APTLY_POOL_PATH=$APTLY_POOL_PATH"
    mkdir -p "$NFS_MIRROR_PATH/pool"
    echo "ln -s $NFS_MIRROR_PATH/pool $APTLY_POOL_PATH"
    ln -s $NFS_MIRROR_PATH/pool $APTLY_POOL_PATH
    echo 'The mount nfs aptly pool is complete'
  displayName: 'Mount and validate the NFS'
  condition: eq('${{ parameters.EnableNFS }}', 'y')
- bash: |
    # Mount storage containers for the aptly db and/or pool of debian mirrors
    EnableNFS=${{ parameters.enableNfs }}
    WORKSPACE=${{ parameters.workspace }}
    MIRROR_NAME=${{ parameters.mirrorName }}
    if [ -z "$StorageAccount" ]; then
      echo "The stroage account not set" 1>&2
      exit 1
    fi
    echo 'Mount storage container aptly for debian mirrors'
    BLOBFUSE_APTLY_DATA=/blobfuse-${StorageAccount}-data
    azure-pipelines/scripts/mirror/mount-storage.sh "$BLOBFUSE_APTLY_DATA" "$StorageAccount" "data" "$StorageAccountSasToken" "/data/blobfuse-${StorageAccount}-data"

    if [ "$MIRROR_NAME" == "none" ]; then
      echo "Skip to make soft link" 
      exit 0
    fi

    mkdir -p "$WORKSPACE"
    APTLY_PATH=$WORKSPACE/aptly
    APTLY_POOL_PATH=$WORKSPACE/pool
    BLOBFUSE_MIRROR_APTLY=$BLOBFUSE_APTLY_DATA/aptly
    BLOBFUSE_MIRROR_PATH=$BLOBFUSE_APTLY_DATA/aptly/$MIRROR_NAME
    [ "$EnableNFS" == "y" ] && BLOBFUSE_MIRROR_PATH=$BLOBFUSE_APTLY_DATA/$MIRROR_NAME/nfs
    echo "APTLY_PATH=$APTLY_PATH, APTLY_POOL_PATH=$APTLY_POOL_PATH"
    mkdir -p "$BLOBFUSE_MIRROR_PATH/pool"
    echo "ln -s $BLOBFUSE_MIRROR_PATH $APTLY_PATH"
    ln -s $BLOBFUSE_MIRROR_PATH $APTLY_PATH
    if [ "$EnableNFS" != "y" ]; then
      echo "Mount Aptly pool, EnableNFS=$EnableNFS"
      echo "ln -s $BLOBFUSE_MIRROR_PATH/pool $APTLY_POOL_PATH"
      ln -s $BLOBFUSE_MIRROR_PATH/pool $APTLY_POOL_PATH
      ln -s "$BLOBFUSE_MIRROR_APTLY" "$WORKSPACE/_aptly"
    fi
    echo 'The mount storage container aptly is complete'
  env:
    StorageAccount: $(StorageAccount)
    StorageAccountSasToken: $(StorageAccountSasToken)
  displayName: 'Mount stroage container to load aptly db and pool script'
- bash: |
    # Mount the publish contianers for debian mirrors
    WORKSPACE=${{ parameters.workspace }}
    PUBLISH_PATH=$WORKSPACE/publish
    PublishToReplica=$(PublishToReplica)
    if [ "$PublishToReplica" == "y" ]; then
        StorageAccount=$StorageAccountReplica
        StorageAccountSasToken=$StorageAccountReplicaSasToken
    fi
    if [ -z "$StorageAccount" ]; then
      echo "The stroage account not set" 1>&2
      exit 1
    fi
    echo 'Mount storage containers for debian mirrors'
    BLOBFUSE_WEB_PATH=/blobfuse-${StorageAccount}-web
    azure-pipelines/scripts/mirror/mount-storage.sh "$BLOBFUSE_WEB_PATH" "$StorageAccount" '$web' "$StorageAccountSasToken" "/data/blobfuse-${StorageAccount}-web"

    mkdir -p $BLOBFUSE_WEB_PATH/debian
    ln -s $BLOBFUSE_WEB_PATH/debian $PUBLISH_PATH
    echo 'The mount storage container web is complete'
  env:
    StorageAccount: $(StorageAccount)
    StorageAccountSasToken: $(StorageAccountSasToken)
    StorageAccountReplica: $(StorageAccountReplica)
    StorageAccountReplicaSasToken: $(StorageAccountReplicaSasToken)
    
  displayName: 'Run mount stroage container to publish mirror script'
