parameters:
- name: 'mirrorNames'
  type: object
  default:
  - stretch
  - buster
- name: 'publishjob'
  type: job
  default:
    job:
    steps:
    - bash: |
        echo "test"
      name: 'test'
      displayName: 'Test'
    - bash: |
        echo "test1"
      name: 'test1'
      displayName: 'Test1'
jobs:
- ${{ each mirrorName in parameters.mirrorNames }}:
  - ${{ each pair in parameters.publishjob }}:
      ${{ if and(ne(pair.key, 'steps'), ne(pair.key, 'job')) }}:
        ${{ pair.key }}: ${{ pair.value }}
    job: ${{ format('Publish_mirror_{0}', mirrorName) }}
    steps:
    - bash: |
        echo "pre-step"
      displayName: 'pre-step'
    - ${{ parameters.publishjob.steps }}
    - bash: |
        echo "post-step"
      displayName: 'post-step'
