stages:
- stage: InitStage
  jobs:
  - job: InitJob
    steps:
    - template: debian-mirror-init.yml
- stage: PublishToPrimaryStage
  variables:
    PublishToReplica: y
  jobs:
  - template: debian-mirror-jobs-publish-mirror.yml
    parameters:
      publishToReplica: y
- stage: MigrateReplicaStage
  dependsOn:
  - InitStage
  - PublishToReplicaStage
  condition: succeeded()
  variables:
  - name: MirrorVersion
    value: $[ stageDependencies.InitStage.InitJob.outputs['InitStep.MirrorVersion'] ]
  - name: PublishToReplica
    value: 'n'
  jobs:
  - job: MigrateReplica
    steps:
    - script: echo skip
    #- template: ../templates/debian-mirror-migrate-replica.yml
- stage: PublishToPrimaryStage
  variables:
    PublishToReplica: n
  jobs:
  - template: debian-mirror-jobs-publish-mirror.yml
    parameters:
      publishToReplica: n
- stage: MigratePrimaryStage
  dependsOn:
  - MigrateReplicaStage
  - PublishToPrimaryStage
  condition: and(succeeded(), eq(stageDependencies.MigrateReplicaStage.outputs['MigrateReplica.CheckVersion.MigrateCdnReplica'], 'y'))
  variables:
  - name: PublishToReplica
    value: 'n'
  - name: MigrateCdnReplica
    value: 'y'
  jobs:
  - job: MigratePrimary
    steps:
    - script: echo skip
    #- template: ../templates/debian-mirror-migrate-primary.yml
- stage: CleanUp
  condition: always()
  jobs:
  - job: CleanUp
    steps:
    - script: echo skip
    - template: ../templates/debian-mirror-cleanup.yml
