parameters:
- name: 'buildNames'
  type: object
  default: ''
- name: 'preSteps'
  type: stepList
  default: []
- name: "postSteps"
  type: stepList
  default: []
- name: 'stepGroups'
  type: object
  default:
  - name: 'none'
    script: ''
    steps: []
- name: 'scriptEnv'
  type: object
  default: ''
- name: 'timeoutInMinutes'
  type: 'number'
  default: 1440
jobs:
- ${{ each build in parameters.stepGroups }}:
  - ${{ if or(eq(parameters.buildNames, ''), containsValue(parameters.buildNames, build.name)) }}:
    - job: ${{  build.name }}
      timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
      variables:
        BUILD_NAME: ${{ build.name }}
      steps:
      - ${{ parameters.preSteps }}
      - ${{ if ne(build.script, '') }}:
        - script: |
            ${{ build.script }}
          env:
            ${{ if ne(parameters.scriptEnv, '') }}:
              ${{ parameters.scriptEnv }}
          displayName: 'BuildScript'
      - ${{ if ne(build.steps, '') }}:
        - ${{ build.steps }}
      - ${{ parameters.postSteps }}
