steps:
- bash: |
    echo 'Try to init disk'
    [ ! -d /data ] && sudo mkdir -p /data
    # Init data disk
    if [ ! -e /dev/disk/azure/scsi1/lun0-part1 ]; then
      echo 'Run parted disk /dev/disk/azure/scsi1/lun0'
      sudo parted /dev/disk/azure/scsi1/lun0 --script mklabel gpt mkpart data ext4 0% 100%
      sleep 10
      sudo mkfs.ext4 /dev/disk/azure/scsi1/lun0-part1
      sudo partprobe /dev/disk/azure/scsi1/lun0-part1
    fi
    # Mount data disk
    echo 'Mount data disk'
    if ! mount | grep -q "/data "; then
      sudo sh -c 'echo "/dev/disk/azure/scsi1/lun0-part1 /data ext4 defaults 0 0" >> /etc/fstab'
      sudo mount -a
    fi
    # Install blobfuse
    echo 'Install blobfuse'
    if ! dpkg -s blobfuse 1>/dev/null 2>&1; then
      wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y blobfuse
    fi
    # Install aptly
    if ! dpkg -s aptly 1>/dev/null 2>&1; then
      sudo apt-get update
      sudo apt-get install -y aptly
    fi
    # Install nfs-common
    if ! dpkg -s nfs-common 1>/dev/null 2>&1; then
      sudo apt-get update
      sudo apt-get install -y nfs-common
    fi
    if ! which az; then
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    fi
  displayName: 'Run prepare mirror agent script'
