steps:
- template: ../templates/prepare-mirror-agent.yaml
- template: ../templates/prepare-mirror-storage.yaml
  parameters:
    storageAccount: $(StorageAccount)
    storageAccountSasToken: $(storageAccountSasToken)
- bash: |
    echo "$(sonic-gpg-enc-private-key)" > "encrypted_private_key.gpg"
    scripts/mirror/aptly.sh "$(CreateDB)" "$(sonic-gpg-passphrase)" $(StorageAccount) "$(Mirror_Name)" "$(Mirror_URL)" "$(Mirror_Distributions)" "$(Mirror_Architectures)" "$(Mirror_Components)"
  displayName: 'Update and publish debian mirrors by aptly'
