parameters:
- name: 'platforms'
  type: object
  default:
  - name: vs
    prestep: 'echo prestep'
    targets: 'target/sonic-vs.bin'
    options:
    poststeps:
    - bash:
- name: 'publishjob'
  type: job
  default:
    job:
    steps:
    - bash: |
        echo "test"
jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ format('Publish_mirror_{0}', platform.name) }}
    timeoutInMinutes: 0
    steps:
    - ${{ if ne(platform.prestep, '') }}:
      - bash: |
          echo "test"
        displayName: 'test1'
    - ${{ if ne(platform.targets, '') }}:
      - bash: |
          echo "pre-step ${{ platform.targets }}"
        displayName: 'pre-step'
    - bash: |
        echo "post"
      displayName: 'post-step'
