parameters:
- name: 'platforms'
  type: object
  default:
  - name: vs
    prestep: 'echo prestep'
    targets: 'target/sonic-vs.bin'
    options:
    poststep:
jobs:
- ${{ each platform in parameters.platforms }}:
  - job: ${{ format('Publish_mirror_{0}', platform.name) }}
    timeoutInMinutes: 0
    steps:
    - ${{ if ne(platform.prestep, '') }}:
      - bash: |
          echo "test"
        displayName: 'Prestep'
    - bash: |
        echo "build step"
      displayName: 'Buildstep'
    - ${{ if ne(platform.targets, '') }}:
      - bash: |
          echo "pre-step ${{ platform.targets }}"
        displayName: 'Poststep'
